### ISSUE TITLE
 Error loading shared library libstdc++.so.6

### ISSUE THREAD

**Issue by eriktux** [python-hyper/brotlipy#33]
Hi,

CoreOS 1068.8.0 (Stable) here, with Docker Server Version: 1.10.3.

I run mitmproxy (dev), the latest version from the docker hub, with this command:
`docker run --rm -it mitmproxy/mitmproxy:dev`

This is what I get:
```
Traceback (most recent call last):
File "/usr/bin/mitmproxy", line 9, in <module>
load_entry_point('mitmproxy==0.18', 'console_scripts', 'mitmproxy')()
File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
return ep.load()
File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
return self.resolve()
File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/lib/python3.5/site-packages/mitmproxy/main.py", line 9, in <module>
from mitmproxy import cmdline
File "/usr/lib/python3.5/site-packages/mitmproxy/cmdline.py", line 9, in <module>
from mitmproxy import filt
File "/usr/lib/python3.5/site-packages/mitmproxy/filt.py", line 40, in <module>
from mitmproxy.models.http import HTTPFlow
File "/usr/lib/python3.5/site-packages/mitmproxy/models/__init__.py", line 3, in <module>
from netlib.http import decoded
File "/usr/lib/python3.5/site-packages/netlib/http/__init__.py", line 2, in <module>
from netlib.http.request import Request
File "/usr/lib/python3.5/site-packages/netlib/http/request.py", line 13, in <module>
from netlib.http import message
File "/usr/lib/python3.5/site-packages/netlib/http/message.py", line 8, in <module>
from netlib import encoding, strutils, basetypes
File "/usr/lib/python3.5/site-packages/netlib/encoding.py", line 11, in <module>
import brotli
File "/usr/lib/python3.5/site-packages/brotli/__init__.py", line 2, in <module>
from .brotli import decompress, Decompressor, compress # noqa
File "/usr/lib/python3.5/site-packages/brotli/brotli.py", line 4, in <module>
from ._brotli import ffi, lib
ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/lib/python3.5/site-packages/brotli/_brotli.cpython-35m-x86_64-linux-gnu.so)
```

**Comment by Lukasa** [comment]
Do you have the installation logs? I have a theory you installed some recently published Linux wheels that look like they have caused a problem.

**Comment by Lukasa** [comment]
Actually, I no longer think this is the fault of the wheels.

Paging @mhils, as this is almost certainly related to mitmproxy/mitmproxy#1451. Good to see you again so soon @mhils!

So when you added brotlipy as a dependency, you also implicitly added a binary dependency on libstdc++.so.6. This is because brotlipy ships a chunk of C++ code as part of libbrotli. That's not normally a problem because most Linux systems have libstdc++.so.6 on them already, but it looks like the mitmproxy docker image does an `apk del g++` after it installs all the Python images. That will almost certainly blow away libstdc++.so.6, which means that brotlipy will no longer be able to execute.

I suspect updating your docker container to keep libstdc++.so.6 around will resolve this problem neatly.

I'd also like to tag @njsmith here: given this problem here, how do you feel about having libstdc++.so in the list of libraries that manylinux1 assumes will be present?

**Comment by mhils** [comment]
I hate binary dependencies :stuck_out_tongue: 

Our docker image now explicitly installs `libstdc++` so that removing `g++` should be ok. 
Dockerhub is building - @eriktux, could you check again once all builds are completed at https://hub.docker.com/r/mitmproxy/mitmproxy/builds/?

Thanks for looking into this @Lukasa! :smiley:

**Comment by Lukasa** [comment]
No problem @mhils, sorry to cause you the trouble (again!).

For what it is worth, I'm trying to ship binary Linux wheels, so at least for brotlipy you shouldn't actually need g++ at install time, at least for us: we just need the `.so` for runetime. =)

**Comment by njsmith** [comment]
> given this problem here, how do you feel about having libstdc++.so in the list of libraries that manylinux1 assumes will be present?

So to be clear: currently, libstdc++.so is in [the list of libraries that manylinux wheels assume to be provided by the system](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) (which is what caused this problem -- your docker image wasn't meeting this requirement), and you're suggesting that maybe this is a mistake and we should require manylinux wheels to bundle their own copies of libstdc++.so?

**Comment by Lukasa** [comment]
@njsmith I wouldn't say I'm *suggesting* that, so much as I'm *wondering* that. Certainly it's clear that, at the very least, Alpine linux doesn't guarantee that a libsdc++.so will be present. It may be that it's sufficient to say "well Alpine is a weird special case", which would be fine by me. But I thought I should flag this case, even if the end result is "ah well, nvm".

**Comment by njsmith** [comment]
Alpine doesn't have glibc either. The only way you can ship a binary that runs on both Alpine and regular systems is to make it, like, a complete self-contained docker image and ship that instead, which rather misses the point. Pip is clever enough that it won't even try installing manylinux wheels when running on Alpine. I'd recommend just not using Alpine for python related things -- the hassle is not worth it.

The more interesting case is mandriva, which is a mostly ordinary system except that they default to a clang/libc++ setup instead of g++/libstdc++. But they still provide a libstdc++ package, exactly because there's lots of third party binaries that assume the system will provide libstdc++ -- it's just that if you use mandriva you have to be clever enough to figure out that you need to install this non-default package.

AFAIK every other reasonable linux distro installs libstdc++ by default.

**Comment by Lukasa** [comment]
Fair enough, I'm happy to call that fine then. =)

**Comment by njsmith** [comment]
Oh, huh, yeah, on further investigation mitmproxy does seem to be using Alpine, so they're opting out of the whole wheel ecosystem and building everything from scratch anyway. (I can't seem to find build logs to confirm this, but that's what should be happening.) And yes, if you build a program using g++ then you definitely cannot then remove the runtime libraries and expect it to work. This has nothing to do with complications of binary distributions :-)

**Comment by eriktux** [comment]
Hey guys, @mhils @Lukasa

sorry for my late reply.

Just a quick msg to let you know that the latest version of mitmproxy (DEV:0.18) from the docker hub is working perfectly now!

Thanks for the fix  :)

**Comment by mhils** [comment]
> it's just that if you use mandriva you have to be clever enough to figure out that you need to install this non-default package.

For reference, this also applies to "LinuxMint 18 (base on Ubuntu 16.04)": https://discourse.mitmproxy.org/t/failed-building-wheel-for-brotlipy-error-message-when-install-using-dev-sh/128

**Comment by njsmith** [comment]
The issue you link to on Linux Mint is totally unrelated to this -- it's someone who's trying to build a package from source (so not using a wheel at all!), and fails because they don't have the necessary compiler.
